import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright config for the TechShop demo — generated by the `/qa` skill.
 *
 * Two local servers are started automatically (reused if already running):
 *   - Frontend (static)  → http://localhost:3000   (`npm start`)
 *   - REST API (Express) → http://localhost:3001   (`npm run start:api`)
 *
 * Override targets with env vars, e.g. to point the browser tests at the
 * live GitHub Pages build:  WEB_URL=https://cristianpgit.github.io/techshop-demo npx playwright test --project=chromium
 */
// Normalize to a trailing slash so relative gotos (`index.html`) resolve under a
// subpath deploy like GitHub Pages (…/techshop-demo/) instead of the origin root.
const WEB_URL = (process.env.WEB_URL || 'http://localhost:3000').replace(/\/+$/, '') + '/';
const API_URL = process.env.API_URL || 'http://localhost:3001';

export default defineConfig({
  testDir: './qa/tests',
  // FAT/local can be slow on first paint; keep generous but not silly.
  timeout: 30_000,
  expect: { timeout: 7_000 },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: [
    ['list'],
    ['html', { outputFolder: 'qa/report', open: 'never' }],
  ],

  projects: [
    {
      name: 'api',
      testDir: './qa/tests/api',
      use: { baseURL: API_URL },
    },
    {
      name: 'chromium',
      testDir: './qa/tests/e2e',
      use: { ...devices['Desktop Chrome'], baseURL: WEB_URL },
    },
    {
      name: 'bugs',
      testDir: './qa/tests/bugs',
      use: { ...devices['Desktop Chrome'], baseURL: WEB_URL },
    },
  ],

  // Only manage local servers when targeting localhost. If WEB_URL/API_URL
  // point elsewhere (e.g. live site), skip the webServer block.
  webServer: WEB_URL.includes('localhost')
    ? [
        {
          command: 'npm start',
          url: 'http://localhost:3000',
          reuseExistingServer: !process.env.CI,
          timeout: 60_000,
        },
        {
          command: 'npm run start:api',
          url: 'http://localhost:3001/api/health',
          reuseExistingServer: !process.env.CI,
          timeout: 60_000,
        },
      ]
    : undefined,
});
